name = "dependent-computability"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DependentComputability"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "a498e40459950bf54efd87d57baf5fb7c0378da6"

[[lean_lib]]
name = "DependentComputability"
